# egohub/constants/canonical_skeleton.py
"""
This file contains constants related to the canonical skeleton definition.
"""

# --- Canonical Skeleton Definition ---
# The following constants define the canonical skeleton based on
# Mediapipe's pose (33 landmarks) and full hand (21 landmarks per hand).
# A virtual 'pelvis' joint is added as the root for hierarchy purposes.
# Hand joints are prefixed with 'left_' or 'right_' and attached to the
# respective wrist.
# All skeletons from source datasets must be remapped to this format.

CANONICAL_SKELETON_JOINTS: list[str] = [
    "pelvis",
    "nose",
    "left_eye_inner",
    "left_eye",
    "left_eye_outer",
    "right_eye_inner",
    "right_eye",
    "right_eye_outer",
    "left_ear",
    "right_ear",
    "mouth_left",
    "mouth_right",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_pinky",
    "right_pinky",
    "left_index",
    "right_index",
    "left_thumb",
    "right_thumb",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
    "left_heel",
    "right_heel",
    "left_foot_index",
    "right_foot_index",
    # Left hand full landmarks (excluding wrist)
    "left_thumb_cmc",
    "left_thumb_mcp",
    "left_thumb_ip",
    "left_thumb_tip",
    "left_index_finger_mcp",
    "left_index_finger_pip",
    "left_index_finger_dip",
    "left_index_finger_tip",
    "left_middle_finger_mcp",
    "left_middle_finger_pip",
    "left_middle_finger_dip",
    "left_middle_finger_tip",
    "left_ring_finger_mcp",
    "left_ring_finger_pip",
    "left_ring_finger_dip",
    "left_ring_finger_tip",
    "left_pinky_mcp",
    "left_pinky_pip",
    "left_pinky_dip",
    "left_pinky_tip",
    # Right hand full landmarks (excluding wrist)
    "right_thumb_cmc",
    "right_thumb_mcp",
    "right_thumb_ip",
    "right_thumb_tip",
    "right_index_finger_mcp",
    "right_index_finger_pip",
    "right_index_finger_dip",
    "right_index_finger_tip",
    "right_middle_finger_mcp",
    "right_middle_finger_pip",
    "right_middle_finger_dip",
    "right_middle_finger_tip",
    "right_ring_finger_mcp",
    "right_ring_finger_pip",
    "right_ring_finger_dip",
    "right_ring_finger_tip",
    "right_pinky_mcp",
    "right_pinky_pip",
    "right_pinky_dip",
    "right_pinky_tip",
]

# Defines the kinematic tree by specifying the parent of each joint.
CANONICAL_SKELETON_HIERARCHY: dict[str, str] = {
    # Body hierarchy (approximated for Mediapipe pose)
    "left_hip": "pelvis",
    "right_hip": "pelvis",
    "left_shoulder": "pelvis",
    "right_shoulder": "pelvis",
    "left_elbow": "left_shoulder",
    "right_elbow": "right_shoulder",
    "left_wrist": "left_elbow",
    "right_wrist": "right_elbow",
    "left_pinky": "left_wrist",
    "right_pinky": "right_wrist",
    "left_index": "left_wrist",
    "right_index": "right_wrist",
    "left_thumb": "left_wrist",
    "right_thumb": "right_wrist",
    "left_knee": "left_hip",
    "right_knee": "right_hip",
    "left_ankle": "left_knee",
    "right_ankle": "right_knee",
    "left_heel": "left_ankle",
    "right_heel": "right_ankle",
    "left_foot_index": "left_heel",
    "right_foot_index": "right_heel",
    "nose": "pelvis",
    "left_eye_inner": "nose",
    "left_eye": "left_eye_inner",
    "left_eye_outer": "left_eye",
    "right_eye_inner": "nose",
    "right_eye": "right_eye_inner",
    "right_eye_outer": "right_eye",
    "left_ear": "left_eye_outer",
    "right_ear": "right_eye_outer",
    "mouth_left": "nose",
    "mouth_right": "nose",
    # Left hand hierarchy
    "left_thumb_cmc": "left_wrist",
    "left_thumb_mcp": "left_thumb_cmc",
    "left_thumb_ip": "left_thumb_mcp",
    "left_thumb_tip": "left_thumb_ip",
    "left_index_finger_mcp": "left_wrist",
    "left_index_finger_pip": "left_index_finger_mcp",
    "left_index_finger_dip": "left_index_finger_pip",
    "left_index_finger_tip": "left_index_finger_dip",
    "left_middle_finger_mcp": "left_wrist",
    "left_middle_finger_pip": "left_middle_finger_mcp",
    "left_middle_finger_dip": "left_middle_finger_pip",
    "left_middle_finger_tip": "left_middle_finger_dip",
    "left_ring_finger_mcp": "left_wrist",
    "left_ring_finger_pip": "left_ring_finger_mcp",
    "left_ring_finger_dip": "left_ring_finger_pip",
    "left_ring_finger_tip": "left_ring_finger_dip",
    "left_pinky_mcp": "left_wrist",
    "left_pinky_pip": "left_pinky_mcp",
    "left_pinky_dip": "left_pinky_pip",
    "left_pinky_tip": "left_pinky_dip",
    # Right hand hierarchy
    "right_thumb_cmc": "right_wrist",
    "right_thumb_mcp": "right_thumb_cmc",
    "right_thumb_ip": "right_thumb_mcp",
    "right_thumb_tip": "right_thumb_ip",
    "right_index_finger_mcp": "right_wrist",
    "right_index_finger_pip": "right_index_finger_mcp",
    "right_index_finger_dip": "right_index_finger_pip",
    "right_index_finger_tip": "right_index_finger_dip",
    "right_middle_finger_mcp": "right_wrist",
    "right_middle_finger_pip": "right_middle_finger_mcp",
    "right_middle_finger_dip": "right_middle_finger_pip",
    "right_middle_finger_tip": "right_middle_finger_dip",
    "right_ring_finger_mcp": "right_wrist",
    "right_ring_finger_pip": "right_ring_finger_mcp",
    "right_ring_finger_dip": "right_ring_finger_pip",
    "right_ring_finger_tip": "right_ring_finger_dip",
    "right_pinky_mcp": "right_wrist",
    "right_pinky_pip": "right_pinky_mcp",
    "right_pinky_dip": "right_pinky_pip",
    "right_pinky_tip": "right_pinky_dip",
}
