metadata:
  source_fps: 30
  target_fps: 30

mano:
  joint_names:
    - "wrist"
    - "thumb1"
    - "thumb2"
    - "thumb3"
    - "thumb_tip"
    - "index1"
    - "index2"
    - "index3"
    - "index_tip"
    - "middle1"
    - "middle2"
    - "middle3"
    - "middle_tip"
    - "ring1"
    - "ring2"
    - "ring3"
    - "ring_tip"
    - "pinky1"
    - "pinky2"
    - "pinky3"
    - "pinky_tip"

  skeleton_hierarchy:
    "thumb1": "wrist"
    "thumb2": "thumb1"
    "thumb3": "thumb2"
    "thumb_tip": "thumb3"
    "index1": "wrist"
    "index2": "index1"
    "index3": "index2"
    "index_tip": "index3"
    "middle1": "wrist"
    "middle2": "middle1"
    "middle3": "middle2"
    "middle_tip": "middle3"
    "ring1": "wrist"
    "ring2": "ring1"
    "ring3": "ring2"
    "ring_tip": "ring3"
    "pinky1": "wrist"
    "pinky2": "pinky1"
    "pinky3": "pinky2"
    "pinky_tip": "pinky3"
