[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "egohub"
version = "0.1.0"
description = "End-to-end Python stack for ingesting, normalizing, and serving egocentric datasets for humanoid robotics research"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.0.0",
    "h5py>=3.8.0",
    "rerun-sdk>=0.23.1",
    "opencv-python-headless>=4.8.0",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "pyyaml>=6.0",
    "tqdm>=4.65.0",
    "einops>=0.8.0",
    "jaxtyping>=0.2.33",
    "beartype>=0.19.0",
    "icecream>=2.1.3",
    "pyserde>=0.20.0",
    "tyro>=0.9.1",
    "pandas>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
]
full = [
    "open3d>=0.17.0",
]

[project.urls]
"Homepage" = "https://github.com/your-repo/egohub"
"Bug Tracker" = "https://github.com/your-repo/egohub/issues"

[tool.setuptools.packages.find]
include = ["egohub*"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 