name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  schedule:
    # Nightly 03:00 UTC full sweep
    - cron: "0 3 * * *"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Core + dev extras
          pip install -e ".[dev]" pytest-cov ruff hypothesis codecov

      # ---------- Static Analysis ---------- #
      - name: Run Ruff (lint)
        run: ruff egohub

      - name: Black formatting check
        run: black --check .

      - name: Mypy type check
        run: mypy egohub

      # ---------- Unit Tests ---------- #
      - name: Run Pytest unit suite with coverage
        run: pytest -m "not integration and not e2e and not perf" --cov=egohub --cov-report=xml --cov-report=term-missing --cov-fail-under=80

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false 